### ISSUE TITLE
NMT copynet and vocabulary sizes

### ISSUE THREAD

**Issue by pteixei** [lspvic/CopyNet#1]
Great job making a Copynet enabled NMT.

I noticed (sadly for my current experiment) that when running copynet enabled NMT,  I have to have both target and source vocabularies with the same number of words, otherwise I get an error. 

Is that a "feature" or a bug? Do I need to send you some context?
Thank you

**Comment by lspvic** [comment]
Yes, currently for nmt, you must use a shared vocabulary for source and target vocabulary, i.e. a `--share_vocab` must be set for nmt command line.  NOT just the same number of words.

It's hard to design totally separated vocabularies for source and target vocabularies, since a part of decoded words are from source sentences.
1). Decoded words indexes must tell which indexes are from source and which are decoded from the target vocabulary. 
2). Source and target vocabulary may have intersection part.
3). It's hard to label the training dataset, especially some decoded words occur multiple times in source sentences.
4). nmt workflow is fixed and changing the nmt workflow is a bad choice.

I think the best solution is to use a shared vocabulary but the first N words are just the target vocabulary and in generate mode, the output words just project to these N words. Notice these N words can contain source words.

Currently the above solution is not implemented and just use the whole shared vocabulary for both generate mode and copy mode.
